-- ============================================================================
-- F1 INSIGHT — Formula 1 Data Warehouse
-- Star Schema DDL (MySQL 8+/9, InnoDB, utf8mb4)
-- ----------------------------------------------------------------------------
-- Dimensions : dim_date, dim_driver, dim_constructor, dim_circuit, dim_race
-- Facts      : fact_race_result, fact_qualifying, fact_lap, fact_pit_stop,
--              fact_driver_standing, fact_constructor_standing
-- Audit      : etl_run_log
--
-- Notes:
--   * Surrogate keys are AUTO_INCREMENT INTs generated by the warehouse.
--   * Natural keys (driver_ref, constructor_ref, circuit_ref, season+round,
--     full_date) are UNIQUE so the ETL load is idempotent (re-runs upsert
--     instead of duplicating).
--   * `season` is denormalised into large fact tables as a degenerate
--     dimension for fast analytical filtering (documented in data_dictionary).
--   * Position Gain (derived metric) = grid - position.
-- ============================================================================

SET NAMES utf8mb4;
SET FOREIGN_KEY_CHECKS = 0;

-- ----------------------------------------------------------------------------
-- DIM_DATE
-- ----------------------------------------------------------------------------
CREATE TABLE IF NOT EXISTS dim_date (
    date_id        INT          NOT NULL AUTO_INCREMENT,
    full_date      DATE         NOT NULL,
    year           SMALLINT     NOT NULL,
    quarter        TINYINT      NOT NULL,
    month          TINYINT      NOT NULL,
    month_name     VARCHAR(12)  NOT NULL,
    day            TINYINT      NOT NULL,
    day_of_week    TINYINT      NOT NULL,
    day_name       VARCHAR(12)  NOT NULL,
    week_of_year   SMALLINT     NOT NULL,
    is_weekend     TINYINT(1)   NOT NULL DEFAULT 0,
    PRIMARY KEY (date_id),
    UNIQUE KEY uq_dim_date_full (full_date),
    KEY ix_dim_date_year (year)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci;

-- ----------------------------------------------------------------------------
-- DIM_DRIVER
-- ----------------------------------------------------------------------------
CREATE TABLE IF NOT EXISTS dim_driver (
    driver_id      INT          NOT NULL AUTO_INCREMENT,
    driver_ref     VARCHAR(64)  NOT NULL,
    code           VARCHAR(8)   NULL,
    forename       VARCHAR(64)  NOT NULL,
    surname        VARCHAR(64)  NOT NULL,
    full_name      VARCHAR(128) NOT NULL,
    number         INT          NULL,
    date_of_birth  DATE         NULL,
    nationality    VARCHAR(64)  NULL,
    url            VARCHAR(255) NULL,
    PRIMARY KEY (driver_id),
    UNIQUE KEY uq_dim_driver_ref (driver_ref),
    KEY ix_dim_driver_surname (surname),
    KEY ix_dim_driver_code (code)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci;

-- ----------------------------------------------------------------------------
-- DIM_CONSTRUCTOR
-- ----------------------------------------------------------------------------
CREATE TABLE IF NOT EXISTS dim_constructor (
    constructor_id   INT          NOT NULL AUTO_INCREMENT,
    constructor_ref  VARCHAR(64)  NOT NULL,
    name             VARCHAR(128) NOT NULL,
    nationality      VARCHAR(64)  NULL,
    url              VARCHAR(255) NULL,
    PRIMARY KEY (constructor_id),
    UNIQUE KEY uq_dim_constructor_ref (constructor_ref),
    KEY ix_dim_constructor_name (name)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci;

-- ----------------------------------------------------------------------------
-- DIM_CIRCUIT
-- ----------------------------------------------------------------------------
CREATE TABLE IF NOT EXISTS dim_circuit (
    circuit_id    INT          NOT NULL AUTO_INCREMENT,
    circuit_ref   VARCHAR(64)  NOT NULL,
    name          VARCHAR(128) NOT NULL,
    location      VARCHAR(64)  NULL,
    country       VARCHAR(64)  NULL,
    latitude      DECIMAL(9,6) NULL,
    longitude     DECIMAL(9,6) NULL,
    altitude      DECIMAL(8,2) NULL,
    url           VARCHAR(255) NULL,
    PRIMARY KEY (circuit_id),
    UNIQUE KEY uq_dim_circuit_ref (circuit_ref),
    KEY ix_dim_circuit_country (country)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci;

-- ----------------------------------------------------------------------------
-- DIM_RACE  (conformed degenerate dimension / mini-dimension of a Grand Prix)
-- ----------------------------------------------------------------------------
CREATE TABLE IF NOT EXISTS dim_race (
    race_id       INT          NOT NULL AUTO_INCREMENT,
    race_ref      VARCHAR(32)  NOT NULL,          -- e.g. '2024-01'
    season        SMALLINT     NOT NULL,
    round         SMALLINT     NOT NULL,
    name          VARCHAR(128) NOT NULL,
    date          DATE         NOT NULL,
    date_id       INT          NOT NULL,
    circuit_id    INT          NOT NULL,
    url           VARCHAR(255) NULL,
    PRIMARY KEY (race_id),
    UNIQUE KEY uq_dim_race_ref (race_ref),
    UNIQUE KEY uq_dim_race_season_round (season, round),
    KEY ix_dim_race_date (date),
    KEY ix_dim_race_circuit (circuit_id),
    CONSTRAINT fk_dim_race_date    FOREIGN KEY (date_id)    REFERENCES dim_date (date_id),
    CONSTRAINT fk_dim_race_circuit FOREIGN KEY (circuit_id) REFERENCES dim_circuit (circuit_id)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci;

-- ----------------------------------------------------------------------------
-- FACT_RACE_RESULT — central performance fact table (one row = driver x race)
-- ----------------------------------------------------------------------------
CREATE TABLE IF NOT EXISTS fact_race_result (
    result_id           BIGINT       NOT NULL AUTO_INCREMENT,
    race_id             INT          NOT NULL,
    driver_id           INT          NOT NULL,
    constructor_id      INT          NOT NULL,
    circuit_id          INT          NOT NULL,
    date_id             INT          NOT NULL,
    season              SMALLINT     NOT NULL,     -- degenerate dimension
    grid                INT          NOT NULL,     -- measure
    position            INT          NULL,         -- measure (NULL = DNF/DSQ)
    position_text       VARCHAR(4)   NULL,
    points              DECIMAL(6,2) NOT NULL DEFAULT 0,
    laps                INT          NOT NULL DEFAULT 0,
    time_milliseconds   BIGINT       NULL,
    fastest_lap_rank    INT          NULL,
    fastest_lap_time    VARCHAR(16)  NULL,
    fastest_lap_seconds DECIMAL(9,3) NULL,
    fastest_lap_speed   DECIMAL(9,3) NULL,
    pit_stop_count      INT          NOT NULL DEFAULT 0,
    status              VARCHAR(48)  NOT NULL,
    position_gain       INT          NULL,         -- DERIVED: grid - position
    PRIMARY KEY (result_id),
    UNIQUE KEY uq_fact_race_result (race_id, driver_id),
    KEY ix_fact_rr_driver (driver_id),
    KEY ix_fact_rr_constructor (constructor_id),
    KEY ix_fact_rr_circuit (circuit_id),
    KEY ix_fact_rr_date (date_id),
    KEY ix_fact_rr_season (season),
    KEY ix_fact_rr_position (position),
    KEY ix_fact_rr_points (points),
    CONSTRAINT fk_fact_rr_race         FOREIGN KEY (race_id)        REFERENCES dim_race (race_id),
    CONSTRAINT fk_fact_rr_driver       FOREIGN KEY (driver_id)      REFERENCES dim_driver (driver_id),
    CONSTRAINT fk_fact_rr_constructor  FOREIGN KEY (constructor_id) REFERENCES dim_constructor (constructor_id),
    CONSTRAINT fk_fact_rr_circuit      FOREIGN KEY (circuit_id)     REFERENCES dim_circuit (circuit_id),
    CONSTRAINT fk_fact_rr_date         FOREIGN KEY (date_id)        REFERENCES dim_date (date_id),
    CONSTRAINT chk_fact_rr_grid        CHECK (grid >= 0)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci;

-- ----------------------------------------------------------------------------
-- FACT_QUALIFYING
-- ----------------------------------------------------------------------------
CREATE TABLE IF NOT EXISTS fact_qualifying (
    qualifying_id  BIGINT       NOT NULL AUTO_INCREMENT,
    race_id        INT          NOT NULL,
    driver_id      INT          NOT NULL,
    constructor_id INT          NOT NULL,
    circuit_id     INT          NOT NULL,
    date_id        INT          NOT NULL,
    season         SMALLINT     NOT NULL,
    position       INT          NOT NULL,
    q1             VARCHAR(16)  NULL,
    q2             VARCHAR(16)  NULL,
    q3             VARCHAR(16)  NULL,
    q1_seconds     DECIMAL(9,3) NULL,
    q2_seconds     DECIMAL(9,3) NULL,
    q3_seconds     DECIMAL(9,3) NULL,
    PRIMARY KEY (qualifying_id),
    UNIQUE KEY uq_fact_qualifying (race_id, driver_id),
    KEY ix_fact_q_driver (driver_id),
    KEY ix_fact_q_constructor (constructor_id),
    KEY ix_fact_q_circuit (circuit_id),
    KEY ix_fact_q_season (season),
    KEY ix_fact_q_position (position),
    CONSTRAINT fk_fact_q_race        FOREIGN KEY (race_id)        REFERENCES dim_race (race_id),
    CONSTRAINT fk_fact_q_driver      FOREIGN KEY (driver_id)      REFERENCES dim_driver (driver_id),
    CONSTRAINT fk_fact_q_constructor FOREIGN KEY (constructor_id) REFERENCES dim_constructor (constructor_id),
    CONSTRAINT fk_fact_q_circuit     FOREIGN KEY (circuit_id)     REFERENCES dim_circuit (circuit_id),
    CONSTRAINT fk_fact_q_date        FOREIGN KEY (date_id)        REFERENCES dim_date (date_id)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci;

-- ----------------------------------------------------------------------------
-- FACT_LAP (largest fact — one row = driver x lap)
-- ----------------------------------------------------------------------------
CREATE TABLE IF NOT EXISTS fact_lap (
    lap_id          BIGINT      NOT NULL AUTO_INCREMENT,
    race_id         INT         NOT NULL,
    driver_id       INT         NOT NULL,
    constructor_id  INT         NOT NULL,
    circuit_id      INT         NOT NULL,
    date_id         INT         NOT NULL,
    season          SMALLINT    NOT NULL,
    lap             INT         NOT NULL,
    position        INT         NULL,     -- position at end of lap (nullable)
    lap_time        VARCHAR(16) NULL,
    lap_milliseconds INT        NULL,
    PRIMARY KEY (lap_id),
    UNIQUE KEY uq_fact_lap (race_id, driver_id, lap),
    KEY ix_fact_lap_driver (driver_id),
    KEY ix_fact_lap_season (season),
    KEY ix_fact_lap_time (lap_milliseconds),
    CONSTRAINT fk_fact_lap_race        FOREIGN KEY (race_id)        REFERENCES dim_race (race_id),
    CONSTRAINT fk_fact_lap_driver      FOREIGN KEY (driver_id)      REFERENCES dim_driver (driver_id),
    CONSTRAINT fk_fact_lap_constructor FOREIGN KEY (constructor_id) REFERENCES dim_constructor (constructor_id),
    CONSTRAINT fk_fact_lap_circuit     FOREIGN KEY (circuit_id)     REFERENCES dim_circuit (circuit_id),
    CONSTRAINT fk_fact_lap_date        FOREIGN KEY (date_id)        REFERENCES dim_date (date_id)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci;

-- ----------------------------------------------------------------------------
-- FACT_PIT_STOP
-- ----------------------------------------------------------------------------
CREATE TABLE IF NOT EXISTS fact_pit_stop (
    pit_stop_id      BIGINT       NOT NULL AUTO_INCREMENT,
    race_id          INT          NOT NULL,
    driver_id        INT          NOT NULL,
    constructor_id   INT          NOT NULL,
    circuit_id       INT          NOT NULL,
    date_id          INT          NOT NULL,
    season           SMALLINT     NOT NULL,
    stop_number      INT          NOT NULL,
    lap              INT          NOT NULL,
    duration         DECIMAL(8,3) NULL,
    duration_ms      INT          NULL,
    PRIMARY KEY (pit_stop_id),
    UNIQUE KEY uq_fact_pit_stop (race_id, driver_id, stop_number),
    KEY ix_fact_ps_driver (driver_id),
    KEY ix_fact_ps_constructor (constructor_id),
    KEY ix_fact_ps_season (season),
    KEY ix_fact_ps_duration (duration),
    CONSTRAINT fk_fact_ps_race        FOREIGN KEY (race_id)        REFERENCES dim_race (race_id),
    CONSTRAINT fk_fact_ps_driver      FOREIGN KEY (driver_id)      REFERENCES dim_driver (driver_id),
    CONSTRAINT fk_fact_ps_constructor FOREIGN KEY (constructor_id) REFERENCES dim_constructor (constructor_id),
    CONSTRAINT fk_fact_ps_circuit     FOREIGN KEY (circuit_id)     REFERENCES dim_circuit (circuit_id),
    CONSTRAINT fk_fact_ps_date        FOREIGN KEY (date_id)        REFERENCES dim_date (date_id)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci;

-- ----------------------------------------------------------------------------
-- FACT_DRIVER_STANDING (snapshot after each round; race_id NULL = final/season)
-- ----------------------------------------------------------------------------
CREATE TABLE IF NOT EXISTS fact_driver_standing (
    standing_id    BIGINT      NOT NULL AUTO_INCREMENT,
    race_id        INT         NULL,
    season         SMALLINT    NOT NULL,
    round          SMALLINT    NOT NULL DEFAULT 0,
    driver_id      INT         NOT NULL,
    constructor_id INT         NULL,
    points         DECIMAL(6,2) NOT NULL DEFAULT 0,
    position       INT         NOT NULL,
    wins           INT         NOT NULL DEFAULT 0,
    PRIMARY KEY (standing_id),
    UNIQUE KEY uq_fact_ds (season, round, driver_id),
    KEY ix_fact_ds_driver (driver_id),
    KEY ix_fact_ds_season (season),
    KEY ix_fact_ds_race (race_id),
    CONSTRAINT fk_fact_ds_race        FOREIGN KEY (race_id)        REFERENCES dim_race (race_id),
    CONSTRAINT fk_fact_ds_driver      FOREIGN KEY (driver_id)      REFERENCES dim_driver (driver_id),
    CONSTRAINT fk_fact_ds_constructor FOREIGN KEY (constructor_id) REFERENCES dim_constructor (constructor_id)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci;

-- ----------------------------------------------------------------------------
-- FACT_CONSTRUCTOR_STANDING
-- ----------------------------------------------------------------------------
CREATE TABLE IF NOT EXISTS fact_constructor_standing (
    standing_id    BIGINT      NOT NULL AUTO_INCREMENT,
    race_id        INT         NULL,
    season         SMALLINT    NOT NULL,
    round          SMALLINT    NOT NULL DEFAULT 0,
    constructor_id INT         NOT NULL,
    points         DECIMAL(6,2) NOT NULL DEFAULT 0,
    position       INT         NOT NULL,
    wins           INT         NOT NULL DEFAULT 0,
    PRIMARY KEY (standing_id),
    UNIQUE KEY uq_fact_cs (season, round, constructor_id),
    KEY ix_fact_cs_constructor (constructor_id),
    KEY ix_fact_cs_season (season),
    KEY ix_fact_cs_race (race_id),
    CONSTRAINT fk_fact_cs_race        FOREIGN KEY (race_id)        REFERENCES dim_race (race_id),
    CONSTRAINT fk_fact_cs_constructor FOREIGN KEY (constructor_id) REFERENCES dim_constructor (constructor_id)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci;

-- ----------------------------------------------------------------------------
-- ETL_AUDIT — one row per pipeline run (data-quality & lineage summary)
-- ----------------------------------------------------------------------------
CREATE TABLE IF NOT EXISTS etl_run_log (
    run_id             BIGINT       NOT NULL AUTO_INCREMENT,
    pipeline           VARCHAR(64)  NOT NULL,
    scope              VARCHAR(128) NOT NULL,
    started_at         DATETIME     NOT NULL,
    finished_at        DATETIME     NULL,
    status             VARCHAR(16)  NOT NULL DEFAULT 'RUNNING',
    records_extracted  INT          NOT NULL DEFAULT 0,
    records_transformed INT         NOT NULL DEFAULT 0,
    records_loaded     INT          NOT NULL DEFAULT 0,
    duplicates_removed INT          NOT NULL DEFAULT 0,
    missing_values_fixed INT        NOT NULL DEFAULT 0,
    errors             INT          NOT NULL DEFAULT 0,
    message            TEXT         NULL,
    PRIMARY KEY (run_id),
    KEY ix_etl_run_status (status)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci;

SET FOREIGN_KEY_CHECKS = 1;
