"""initial star schema

Revision ID: aede124d691a
Revises: 
Create Date: 2026-10-09 01:39:36.502295

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'aede124d691a'
down_revision: Union[str, Sequence[str], None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('dim_circuit',
    sa.Column('circuit_id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('circuit_ref', sa.String(length=64), nullable=False),
    sa.Column('name', sa.String(length=128), nullable=False),
    sa.Column('location', sa.String(length=64), nullable=True),
    sa.Column('country', sa.String(length=64), nullable=True),
    sa.Column('latitude', sa.Numeric(precision=9, scale=6), nullable=True),
    sa.Column('longitude', sa.Numeric(precision=9, scale=6), nullable=True),
    sa.Column('altitude', sa.Numeric(precision=8, scale=2), nullable=True),
    sa.Column('url', sa.String(length=255), nullable=True),
    sa.PrimaryKeyConstraint('circuit_id'),
    sa.UniqueConstraint('circuit_ref')
    )
    op.create_table('dim_constructor',
    sa.Column('constructor_id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('constructor_ref', sa.String(length=64), nullable=False),
    sa.Column('name', sa.String(length=128), nullable=False),
    sa.Column('nationality', sa.String(length=64), nullable=True),
    sa.Column('url', sa.String(length=255), nullable=True),
    sa.PrimaryKeyConstraint('constructor_id'),
    sa.UniqueConstraint('constructor_ref')
    )
    op.create_table('dim_date',
    sa.Column('date_id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('full_date', sa.Date(), nullable=False),
    sa.Column('year', sa.SmallInteger(), nullable=False),
    sa.Column('quarter', sa.SmallInteger(), nullable=False),
    sa.Column('month', sa.SmallInteger(), nullable=False),
    sa.Column('month_name', sa.String(length=12), nullable=False),
    sa.Column('day', sa.SmallInteger(), nullable=False),
    sa.Column('day_of_week', sa.SmallInteger(), nullable=False),
    sa.Column('day_name', sa.String(length=12), nullable=False),
    sa.Column('week_of_year', sa.SmallInteger(), nullable=False),
    sa.Column('is_weekend', sa.Boolean(), nullable=False),
    sa.PrimaryKeyConstraint('date_id'),
    sa.UniqueConstraint('full_date')
    )
    op.create_table('dim_driver',
    sa.Column('driver_id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('driver_ref', sa.String(length=64), nullable=False),
    sa.Column('code', sa.String(length=8), nullable=True),
    sa.Column('forename', sa.String(length=64), nullable=False),
    sa.Column('surname', sa.String(length=64), nullable=False),
    sa.Column('full_name', sa.String(length=128), nullable=False),
    sa.Column('number', sa.Integer(), nullable=True),
    sa.Column('date_of_birth', sa.Date(), nullable=True),
    sa.Column('nationality', sa.String(length=64), nullable=True),
    sa.Column('url', sa.String(length=255), nullable=True),
    sa.PrimaryKeyConstraint('driver_id'),
    sa.UniqueConstraint('driver_ref')
    )
    op.create_table('etl_run_log',
    sa.Column('run_id', sa.BigInteger(), autoincrement=True, nullable=False),
    sa.Column('pipeline', sa.String(length=64), nullable=False),
    sa.Column('scope', sa.String(length=128), nullable=False),
    sa.Column('started_at', sa.DateTime(), nullable=False),
    sa.Column('finished_at', sa.DateTime(), nullable=True),
    sa.Column('status', sa.String(length=16), nullable=False),
    sa.Column('records_extracted', sa.Integer(), nullable=False),
    sa.Column('records_transformed', sa.Integer(), nullable=False),
    sa.Column('records_loaded', sa.Integer(), nullable=False),
    sa.Column('duplicates_removed', sa.Integer(), nullable=False),
    sa.Column('missing_values_fixed', sa.Integer(), nullable=False),
    sa.Column('errors', sa.Integer(), nullable=False),
    sa.Column('message', sa.Text(), nullable=True),
    sa.PrimaryKeyConstraint('run_id')
    )
    op.create_table('dim_race',
    sa.Column('race_id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('race_ref', sa.String(length=32), nullable=False),
    sa.Column('season', sa.SmallInteger(), nullable=False),
    sa.Column('round', sa.SmallInteger(), nullable=False),
    sa.Column('name', sa.String(length=128), nullable=False),
    sa.Column('date', sa.Date(), nullable=False),
    sa.Column('date_id', sa.Integer(), nullable=False),
    sa.Column('circuit_id', sa.Integer(), nullable=False),
    sa.Column('url', sa.String(length=255), nullable=True),
    sa.ForeignKeyConstraint(['circuit_id'], ['dim_circuit.circuit_id'], ),
    sa.ForeignKeyConstraint(['date_id'], ['dim_date.date_id'], ),
    sa.PrimaryKeyConstraint('race_id'),
    sa.UniqueConstraint('race_ref')
    )
    op.create_table('fact_constructor_standing',
    sa.Column('standing_id', sa.BigInteger(), autoincrement=True, nullable=False),
    sa.Column('race_id', sa.Integer(), nullable=True),
    sa.Column('season', sa.SmallInteger(), nullable=False),
    sa.Column('round', sa.SmallInteger(), nullable=False),
    sa.Column('constructor_id', sa.Integer(), nullable=False),
    sa.Column('points', sa.Numeric(precision=6, scale=2), nullable=False),
    sa.Column('position', sa.Integer(), nullable=False),
    sa.Column('wins', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['constructor_id'], ['dim_constructor.constructor_id'], ),
    sa.ForeignKeyConstraint(['race_id'], ['dim_race.race_id'], ),
    sa.PrimaryKeyConstraint('standing_id'),
    sa.UniqueConstraint('season', 'round', 'constructor_id', name='uq_fact_cs')
    )
    op.create_table('fact_driver_standing',
    sa.Column('standing_id', sa.BigInteger(), autoincrement=True, nullable=False),
    sa.Column('race_id', sa.Integer(), nullable=True),
    sa.Column('season', sa.SmallInteger(), nullable=False),
    sa.Column('round', sa.SmallInteger(), nullable=False),
    sa.Column('driver_id', sa.Integer(), nullable=False),
    sa.Column('constructor_id', sa.Integer(), nullable=True),
    sa.Column('points', sa.Numeric(precision=6, scale=2), nullable=False),
    sa.Column('position', sa.Integer(), nullable=False),
    sa.Column('wins', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['constructor_id'], ['dim_constructor.constructor_id'], ),
    sa.ForeignKeyConstraint(['driver_id'], ['dim_driver.driver_id'], ),
    sa.ForeignKeyConstraint(['race_id'], ['dim_race.race_id'], ),
    sa.PrimaryKeyConstraint('standing_id'),
    sa.UniqueConstraint('season', 'round', 'driver_id', name='uq_fact_ds')
    )
    op.create_table('fact_lap',
    sa.Column('lap_id', sa.BigInteger(), autoincrement=True, nullable=False),
    sa.Column('race_id', sa.Integer(), nullable=False),
    sa.Column('driver_id', sa.Integer(), nullable=False),
    sa.Column('constructor_id', sa.Integer(), nullable=False),
    sa.Column('circuit_id', sa.Integer(), nullable=False),
    sa.Column('date_id', sa.Integer(), nullable=False),
    sa.Column('season', sa.SmallInteger(), nullable=False),
    sa.Column('lap', sa.Integer(), nullable=False),
    sa.Column('position', sa.Integer(), nullable=True),
    sa.Column('lap_time', sa.String(length=16), nullable=True),
    sa.Column('lap_milliseconds', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['circuit_id'], ['dim_circuit.circuit_id'], ),
    sa.ForeignKeyConstraint(['constructor_id'], ['dim_constructor.constructor_id'], ),
    sa.ForeignKeyConstraint(['date_id'], ['dim_date.date_id'], ),
    sa.ForeignKeyConstraint(['driver_id'], ['dim_driver.driver_id'], ),
    sa.ForeignKeyConstraint(['race_id'], ['dim_race.race_id'], ),
    sa.PrimaryKeyConstraint('lap_id'),
    sa.UniqueConstraint('race_id', 'driver_id', 'lap', name='uq_fact_lap')
    )
    op.create_table('fact_pit_stop',
    sa.Column('pit_stop_id', sa.BigInteger(), autoincrement=True, nullable=False),
    sa.Column('race_id', sa.Integer(), nullable=False),
    sa.Column('driver_id', sa.Integer(), nullable=False),
    sa.Column('constructor_id', sa.Integer(), nullable=False),
    sa.Column('circuit_id', sa.Integer(), nullable=False),
    sa.Column('date_id', sa.Integer(), nullable=False),
    sa.Column('season', sa.SmallInteger(), nullable=False),
    sa.Column('stop_number', sa.Integer(), nullable=False),
    sa.Column('lap', sa.Integer(), nullable=False),
    sa.Column('duration', sa.Numeric(precision=8, scale=3), nullable=True),
    sa.Column('duration_ms', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['circuit_id'], ['dim_circuit.circuit_id'], ),
    sa.ForeignKeyConstraint(['constructor_id'], ['dim_constructor.constructor_id'], ),
    sa.ForeignKeyConstraint(['date_id'], ['dim_date.date_id'], ),
    sa.ForeignKeyConstraint(['driver_id'], ['dim_driver.driver_id'], ),
    sa.ForeignKeyConstraint(['race_id'], ['dim_race.race_id'], ),
    sa.PrimaryKeyConstraint('pit_stop_id'),
    sa.UniqueConstraint('race_id', 'driver_id', 'stop_number', name='uq_fact_pit_stop')
    )
    op.create_table('fact_qualifying',
    sa.Column('qualifying_id', sa.BigInteger(), autoincrement=True, nullable=False),
    sa.Column('race_id', sa.Integer(), nullable=False),
    sa.Column('driver_id', sa.Integer(), nullable=False),
    sa.Column('constructor_id', sa.Integer(), nullable=False),
    sa.Column('circuit_id', sa.Integer(), nullable=False),
    sa.Column('date_id', sa.Integer(), nullable=False),
    sa.Column('season', sa.SmallInteger(), nullable=False),
    sa.Column('position', sa.Integer(), nullable=False),
    sa.Column('q1', sa.String(length=16), nullable=True),
    sa.Column('q2', sa.String(length=16), nullable=True),
    sa.Column('q3', sa.String(length=16), nullable=True),
    sa.Column('q1_seconds', sa.Numeric(precision=9, scale=3), nullable=True),
    sa.Column('q2_seconds', sa.Numeric(precision=9, scale=3), nullable=True),
    sa.Column('q3_seconds', sa.Numeric(precision=9, scale=3), nullable=True),
    sa.ForeignKeyConstraint(['circuit_id'], ['dim_circuit.circuit_id'], ),
    sa.ForeignKeyConstraint(['constructor_id'], ['dim_constructor.constructor_id'], ),
    sa.ForeignKeyConstraint(['date_id'], ['dim_date.date_id'], ),
    sa.ForeignKeyConstraint(['driver_id'], ['dim_driver.driver_id'], ),
    sa.ForeignKeyConstraint(['race_id'], ['dim_race.race_id'], ),
    sa.PrimaryKeyConstraint('qualifying_id'),
    sa.UniqueConstraint('race_id', 'driver_id', name='uq_fact_qualifying')
    )
    op.create_table('fact_race_result',
    sa.Column('result_id', sa.BigInteger(), autoincrement=True, nullable=False),
    sa.Column('race_id', sa.Integer(), nullable=False),
    sa.Column('driver_id', sa.Integer(), nullable=False),
    sa.Column('constructor_id', sa.Integer(), nullable=False),
    sa.Column('circuit_id', sa.Integer(), nullable=False),
    sa.Column('date_id', sa.Integer(), nullable=False),
    sa.Column('season', sa.SmallInteger(), nullable=False),
    sa.Column('grid', sa.Integer(), nullable=False),
    sa.Column('position', sa.Integer(), nullable=True),
    sa.Column('position_text', sa.String(length=4), nullable=True),
    sa.Column('points', sa.Numeric(precision=6, scale=2), nullable=False),
    sa.Column('laps', sa.Integer(), nullable=False),
    sa.Column('time_milliseconds', sa.BigInteger(), nullable=True),
    sa.Column('fastest_lap_rank', sa.Integer(), nullable=True),
    sa.Column('fastest_lap_time', sa.String(length=16), nullable=True),
    sa.Column('fastest_lap_seconds', sa.Numeric(precision=9, scale=3), nullable=True),
    sa.Column('fastest_lap_speed', sa.Numeric(precision=9, scale=3), nullable=True),
    sa.Column('pit_stop_count', sa.Integer(), nullable=False),
    sa.Column('status', sa.String(length=48), nullable=False),
    sa.Column('position_gain', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['circuit_id'], ['dim_circuit.circuit_id'], ),
    sa.ForeignKeyConstraint(['constructor_id'], ['dim_constructor.constructor_id'], ),
    sa.ForeignKeyConstraint(['date_id'], ['dim_date.date_id'], ),
    sa.ForeignKeyConstraint(['driver_id'], ['dim_driver.driver_id'], ),
    sa.ForeignKeyConstraint(['race_id'], ['dim_race.race_id'], ),
    sa.PrimaryKeyConstraint('result_id'),
    sa.UniqueConstraint('race_id', 'driver_id', name='uq_fact_race_result')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('fact_race_result')
    op.drop_table('fact_qualifying')
    op.drop_table('fact_pit_stop')
    op.drop_table('fact_lap')
    op.drop_table('fact_driver_standing')
    op.drop_table('fact_constructor_standing')
    op.drop_table('dim_race')
    op.drop_table('etl_run_log')
    op.drop_table('dim_driver')
    op.drop_table('dim_date')
    op.drop_table('dim_constructor')
    op.drop_table('dim_circuit')
    # ### end Alembic commands ###
